### ISSUE TITLE
I found a hug!!!!!

### ISSUE THREAD

**Issue by JackYang1008** [HandsomeHans/C-OF#3]
Hi, I found a BUG in your code
 
In the script "cof_main.py" in line 152:
```python
if similarity[i] > simmed:
     self.points1[k] = self.points1[i]
     self.points2[k] = self.points2[i]
```
should be revised to 
```python
if similarity[i] >= simmed:
     self.points1[k] = self.points1[i]
     self.points2[k] = self.points2[i]
```
Otherwise, when simmed=1,  the following code will not be executed, the attribute self.tracking=False, the whole tracking processing will be skipped.

**Comment by HansRen1024** [comment]
Hi, thank you for pointing out this.  simmed is the median value of the similarities. So it should not matter if there is an equal sign or not.

**Comment by JackYang1008** [comment]
Actually, I tested my video (the face in the video is almost static) using the original script, and the result was terrible. By checking the variable, I found my median values of the similarities were always 1, making the attribute "self.tracking" automatically being "False".  After modification, it works.

**Comment by HansRen1024** [comment]
Hi, I have checked the video you sent to me. Yeah, you are right. In some scenarios, the values in the similarity list are all 1.0, which may cause a failure tracking problem. I appreciate your work. A PR is most welcome, which can count you as a contributor.
